port: 10230
url: ''
self_key: ''
image_root: '/images'
log_image_root: '/log_images'
line:
  secret: ''
  access: ''
twitch:
  client_id: ''
  client_secret: ''
  sub_secret: ''
  chat_host: ''
  bot_oauth: ''
  bot_user: ''
google:
  api_key: ''
database:
  host: 'localhost'
  port: 5432
  user: 'postgres'
  pass: ''
  dbname: 'mtfosbot'
redis:
  host: 'localhost'
  port: 6379
elasticsearch:
  host: 'http://localhost:9200'
  index: 'mtfosbot'